using Core.Common.Contracts;
using Moq;
using System;
using System.Linq;
using MyBoilerPlate.Data;
using MyBoilerPlate.Business.Entities;
using MyBoilerPlate.Business.Engines;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyBoilerPlate.Business.Engines.Contracts;
using MyBoilerPlate.Business.Entities.DTOs;
using System.Collections.Generic;
using MyBoilerPlate.Business;
using Microsoft.Extensions.DependencyInjection;
using System.Threading.Tasks;
using MyBoilerPlate.Tests.Installers;
using MyBoilerPlate.Web.Infrastructure.Services;

namespace MyBoilerPlate.Tests.Repositories
{
    [TestClass]
    public class FakeRepositoryTest : TestBase
    {
        private IDataRepositoryFactory _DataRepositoryFactory;

        [TestInitialize]
        public void Setup()
        {
            this.Initialize((services, configuration) =>
            {
                services.AddHttpContextService(configuration);
                services.AddDataServices(configuration);
                services.AddFakeRepositoryServices(configuration);
            });

            _DataRepositoryFactory = ObjectContainer.GetService<IDataRepositoryFactory>();
        }

        [TestMethod]
        public async Task FakeAutogeneratedIds()
        {
            // Arrange
            var employees = new List<Employee>()
            {
                new Employee { FirstName = "Employee A"},
                new Employee { FirstName = "Employee B"},
                new Employee { FirstName = "Employee C"},
                new Employee { FirstName = "Employee D"},
            };

            var repo = _DataRepositoryFactory.GetDataRepository<Employee>();

            // Act
            await repo.AddRangeAsync(employees);

            // Assert
            foreach(var item in employees)
            {
                Assert.IsTrue(item.Id > 0);
            }
        }

        [TestMethod]
        public void GetUnitOfWork()
        {
            var unitOfWork = _DataRepositoryFactory.GetUnitOfWork();

            using (var transaction = unitOfWork.CreateTransaction())
            {
                transaction.Commit();
            }

            Assert.IsNull(null);
        }
    }
}
